name    'loispuig-pagespeed'
version '0.1.0'
source 'git://github.com/loispuig/puppet-pagespeed.git'
author 'Loïs PUIG'
license 'MIT'
summary 'Puppet module for downloading Google pagespeed web server module'
description ''
project_page 'https://github.com/loispuig/puppet-pagespeed'
dependency 'puppetlabs/vcsrepo', '>= 4.5.0 < 5.0.0'
